# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f192f0d7230dad83ae4df55b63a0bb6d4ec4d0f51b73be837946e94dcb1b35bd51228dd24969ccb3f15cbf3457ac8d6f5dec2b84b8b21054116dd74129fbb02b

test:
  secret_key_base: 548ff7b93045e1bc7ee11c01362321a98054c7db5f7a497766feb6a280f46e48af40af1800e4c5f4ad68c37654c1322588308c0e7845199b3d036e765a715de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
